queue_rules:
  - name: default
    queue_conditions:
      - author=scala-steward
      - status-success=validate
      - body~=labels:.*semver-patch
    merge_conditions:
      - author=scala-steward
      - status-success=validate
      - body~=labels:.*semver-patch
    merge_method: merge

pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions: []
    actions:
      queue:
