apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-initdb-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /initdb/postgres
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-initdb-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi
