name: CI
on: [ pull_request, push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Spin up Test Environment
        run: docker-compose up -d
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Build and Test
        run: sbt -v -Dfile.encoding=UTF-8 +check +test +coverage
