name: CI
on:
  pull_request:
    paths-ignore:
      - '*.md'
      - LICENSE
  push:
    paths-ignore:
      - '*.md'
      - LICENSE
jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      STATION: Barcelona
      CONNECTED_STATIONS: Madrid,Valencia
      JDBC_PASSWORD: changeme
      CI: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Spin up Test Environment
        run: docker-compose up -d
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Build and Test
        run: |
          sbt -v -Dfile.encoding=UTF-8 +check +coverage +test +coverageReport
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1 -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1         -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                       -name "*.lock"               -delete || true
      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}